### DISCUSSION TITLE
CSS 프레임워크

### DISCUSSION THREAD

**Discussion by guesung** [dnd-side-project/dnd-9th-5-frontend#3] [General]
# 1. styled-component
# 2. tailwind

**Comment by seondal** [comment]
[카카오웹툰은 CSS를 어떻게 작성하고있을까?](https://fe-developers.kakaoent.com/2022/220210-css-in-kakaowebtoon/)

CSS in JS 의 성능이슈로 인해 tailwind css 를 쓰고 tailwind로 안되는 부분들만 CSS Module을 사용함.
다만 규모가 엄청 크고 성능이 크게 중요하지 않은 프로젝트에서는 빠르게 작성하고 테스트하기 쉬운 CSS in JS가 여전히 낫다

**Comment by seondal** [comment]
살짝 별개의 내용이긴 하지만 저희가 컬러코드를 어떻게 저장할지도 생각해봐야할 것 같아요!

프론트엔드 개발 시 컬러코드를 관리하는 방법은 여러 가지가 있습니다. 이 중에서 가장 흔히 사용되는 방법 두 가지를 설명하겠습니다.

1. 변수 또는 상수를 사용하여 관리:
   CSS에서 컬러코드를 변수 또는 상수로 정의하여 관리하는 방법입니다. 이는 CSS 프리프로세서(예: Sass, Less)를 사용할 때 특히 유용합니다. 변수를 사용하면 전체 프로젝트에서 일관된 컬러테마를 쉽게 변경하거나 재사용할 수 있습니다.

   예를 들어, Sass를 사용하여 컬러코드를 변수로 관리하는 방법은 다음과 같습니다:

   ```scss
   // 컬러코드 변수 정의
   $primary-color: #007bff;
   $secondary-color: #6c757d;
   $text-color: #333;

   // 스타일 적용 예시
   .button {
     background-color: $primary-color;
     color: $text-color;
   }
   ```

   이렇게 변수로 정의된 컬러코드는 프로젝트 내에서 재사용하거나 테마를 변경할 때 편리하게 관리할 수 있습니다.

2. 테마 관리 라이브러리 사용:
   프론트엔드 프레임워크나 라이브러리에서는 컬러테마 관리를 도와주는 테마 관리 라이브러리를 제공하기도 합니다. 이러한 라이브러리를 사용하면 컬러코드를 중앙에서 효율적으로 관리할 수 있고, 테마를 쉽게 교체하거나 변경할 수 있습니다.

   예를 들어, React용으로는 `styled-components`와 같은 라이브러리가 있습니다. 이 라이브러리는 컴포넌트 스타일을 정의할 때 JavaScript 템플릿 리터럴 문법을 사용하며, 변수 또는 상수를 이용하여 컬러코드를 관리할 수 있습니다.

   ```jsx
   import styled from 'styled-components';

   // 컬러코드 변수 정의
   const primaryColor = '#007bff';
   const secondaryColor = '#6c757d';
   const textColor = '#333';

   // 스타일 컴포넌트 예시
   const Button = styled.button`
     background-color: ${primaryColor};
     color: ${textColor};
   `;
   ```

   이런 방식으로 `styled-components` 또는 비슷한 라이브러리를 사용하면 컴포넌트 스타일을 컬러테마와 연결하여 관리할 수 있습니다.

어떤 방식을 사용하든, 컬러코드를 관리하는 것은 일관성을 유지하고 유지보수를 쉽게 하기 위해 중요합니다. 선택한 방식은 프로젝트 요구사항과 팀의 개발 스타일에 따라 다를 수 있습니다.
